In [1]:
a=[1,2,3,4]
b=[2,3,4,5]

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [4]:
a=np.array([1,2,3,4,5])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([3.14,2,3,4])

array([3.14, 2.  , 3.  , 4.  ])

In [7]:
np.array([3.14,2,3,4], dtype=np.float32)

array([3.14, 2.  , 3.  , 4.  ], dtype=float32)

###  <font color='red'>Create an array of only zeros</font>
np.zeros(10)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

###  <font color='red'>Create an array of only ones</font>
np.ones((3,5),dtype=int)

In [9]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

###  <font color='red'>Create an array of only the numbers we want</font>
np.full((3,5),3)

In [10]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

###  <font color='red'>Create an increasing array from one number to a number at regular intervals</font>
np.arange(0,31,3)

In [11]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

###  <font color='red'>Create an array of as many numbers as we want between certain numbers</font>
np.linspace(0,1,10)

In [12]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

###  <font color='red'>Create a random matrix whose mean and standard deviation we determine</font>
np.random.normal(10,4,(3,4))

In [13]:
np.random.normal(10,4,(3,4))

array([[15.65623633, 10.33546658, 16.35445603,  8.18915889],
       [15.61983447,  7.08944395,  8.15618762,  3.61464851],
       [ 6.67638119, 18.07442945, 11.41424549,  9.56027222]])

###  <font color='red'>Create a random integer matrix in a specified range</font>
np.random.randint(0,10,(3,3))

In [14]:
np.random.randint(0,10,(3,3))

array([[9, 7, 0],
       [8, 1, 2],
       [2, 2, 7]])

* ndim: number of dimensions
* shape: size information
* size: number of elements
* dtype: data type

In [15]:
a=np.random.randint(10,size=10)

In [16]:
a

array([9, 2, 2, 5, 0, 3, 7, 1, 7, 9])

In [17]:
a.ndim

1

In [18]:
a.shape

(10,)

In [19]:
a.size

10

In [20]:
a.dtype

dtype('int32')

In [21]:
b=np.random.randint(10,size=(3,5))


In [22]:
b.ndim

2

In [23]:
b.shape

(3, 5)

In [24]:
b.size

15

In [25]:
b.dtype

dtype('int32')

###  <font color='red'>Reshaping an array or matrix</font>
a.reshape((3,3))

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
a=np.arange(1,10)

In [29]:
a.ndim

1

In [30]:
a=a.reshape((3,3))

In [31]:
a.ndim

2

###  <font color='red'>Concatenation</font> 
**np.concatenate([a,a])** **vertical**

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**np.concatenate([a,a],axis=1)**  **horizontal**

array([[1, 2, 3, 1, 2, 3],
[4, 5, 6, 4, 5, 6],
[7, 8, 9, 7, 8, 9]])
       

In [32]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [33]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [34]:
z=np.array([7,8,9])

In [35]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

In [37]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

###  <font color='red'>Splitting</font>

np.split(x,[3,5])

np.hsplit(m,[2]) **horizontal**

np.vsplit(m,[2]) **vertical**

In [39]:
x=np.array([1,2,3,99,99,3,2,1])
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [40]:
a,b,c=np.split(x,[3,5])

In [41]:
a

array([1, 2, 3])

In [42]:
b

array([99, 99])

In [43]:
c

array([3, 2, 1])

In [44]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
ust ,alt=np.vsplit(m,[2])
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [46]:
sol,sag=np.hsplit(m,[2])
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

###  <font color='red'>Sorting</font>

np.sort(v)

np.sort(b, axis=1) **horizontal**

np.sort(b, axis=0) **vertical**

In [47]:
v=np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [48]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [49]:
b=np.random.normal(20,5,(3,3))
b

array([[23.45275082, 23.07786392, 27.23625018],
       [15.84578374, 23.64956619, 27.56903991],
       [16.96071764, 20.85463024, 26.49086389]])

In [50]:
np.sort(b, axis=1)

array([[23.07786392, 23.45275082, 27.23625018],
       [15.84578374, 23.64956619, 27.56903991],
       [16.96071764, 20.85463024, 26.49086389]])

In [51]:
np.sort(b, axis=0)

array([[15.84578374, 20.85463024, 26.49086389],
       [16.96071764, 23.07786392, 27.23625018],
       [23.45275082, 23.64956619, 27.56903991]])

###  <font color='red'>Accessing elements with index</font>

In [52]:
a=np.random.randint(10, size=10)
a

array([4, 1, 4, 7, 2, 0, 7, 9, 3, 5])

In [53]:
a[0]

4

In [54]:
m=np.random.randint(10, size=(3,5))
m

array([[7, 2, 8, 1, 9],
       [5, 9, 0, 3, 0],
       [3, 6, 1, 0, 6]])

In [55]:
m[0,0]

7

In [56]:
m[0,3]

1

In [57]:
m[0,3]=100
m

array([[  7,   2,   8, 100,   9],
       [  5,   9,   0,   3,   0],
       [  3,   6,   1,   0,   6]])

In [58]:
m[1,3]=2.2
m

array([[  7,   2,   8, 100,   9],
       [  5,   9,   0,   2,   0],
       [  3,   6,   1,   0,   6]])

###  <font color='red'>Accessing elements with slicing</font>

In [59]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
a[0:3]

array([20, 21, 22])

In [61]:
a[:3]

array([20, 21, 22])

In [62]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [63]:
a[1::2]

array([21, 23, 25, 27, 29])

In [64]:
a[0::2]

array([20, 22, 24, 26, 28])

In [65]:
a[0::3]

array([20, 23, 26, 29])

In [66]:
m=np.random.randint(10,size=(5,5))
m

array([[2, 9, 4, 3, 6],
       [0, 2, 1, 0, 1],
       [4, 7, 3, 5, 2],
       [8, 7, 9, 6, 6],
       [7, 2, 7, 4, 8]])

In [67]:
m[:,0]

array([2, 0, 4, 8, 7])

In [68]:
m[0,:]

array([2, 9, 4, 3, 6])

In [69]:
m[0:2,0:3]

array([[2, 9, 4],
       [0, 2, 1]])

In [70]:
m[:,:2]

array([[2, 9],
       [0, 2],
       [4, 7],
       [8, 7],
       [7, 2]])

In [71]:
m[1:3,0:2]

array([[0, 2],
       [4, 7]])

### <font color='red'>Manipulating subarrays</font> 

In [72]:
a=np.random.randint(10, size=(5,5))
a

array([[8, 9, 7, 4, 0],
       [5, 9, 0, 6, 0],
       [8, 0, 9, 9, 5],
       [2, 8, 4, 4, 3],
       [3, 7, 5, 7, 7]])

In [73]:
sub_a=a[0:3,0:2]
sub_a

array([[8, 9],
       [5, 9],
       [8, 0]])

In [74]:
sub_a[0,0]=999
sub_a[1,1]=888

In [75]:
sub_a

array([[999,   9],
       [  5, 888],
       [  8,   0]])

In [76]:
a

array([[999,   9,   7,   4,   0],
       [  5, 888,   0,   6,   0],
       [  8,   0,   9,   9,   5],
       [  2,   8,   4,   4,   3],
       [  3,   7,   5,   7,   7]])

In [77]:
m=np.random.randint(10, size=(5,5))
m

array([[6, 8, 0, 3, 3],
       [0, 9, 9, 1, 4],
       [7, 2, 9, 2, 0],
       [8, 8, 9, 8, 7],
       [3, 5, 5, 8, 6]])

In [78]:
sub_m=m[0:3,0:2].copy()
sub_m

array([[6, 8],
       [0, 9],
       [7, 2]])

In [79]:
sub_m[0,0]=9999

In [80]:
sub_m , m 

(array([[9999,    8],
        [   0,    9],
        [   7,    2]]),
 array([[6, 8, 0, 3, 3],
        [0, 9, 9, 1, 4],
        [7, 2, 9, 2, 0],
        [8, 8, 9, 8, 7],
        [3, 5, 5, 8, 6]]))

### <font color='red'>Accessing elements with fancy index </font>

In [81]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [82]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [83]:
bring=[1,3,5]
v[bring]

array([ 3,  9, 15])

#### for matrix

In [84]:
m=np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
rows=np.array([0,1])
columns=np.array([1,2])
m[rows,columns]

array([1, 5])

#### fancy index with basic index

In [86]:
m[0,[1,2]]

array([1, 2])

#### fancy index with slicing

In [87]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

### <font color='red'>Conditional element operations</font> 

In [88]:
v=np.array([1, 2, 3, 4, 5])

In [89]:
v>5

array([False, False, False, False, False])

In [90]:
v[v>3]

array([4, 5])

In [91]:
v[v>=3]

array([3, 4, 5])

In [92]:
v[v<3]

array([1, 2])

In [93]:
v[v<=3]

array([1, 2, 3])

In [94]:
v[v!=3]

array([1, 2, 4, 5])

In [95]:
v*2

array([ 2,  4,  6,  8, 10])

In [96]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [97]:
v**2

array([ 1,  4,  9, 16, 25])

### <font color='red'>Mathematical operations</font> 

In [98]:
v=np.array([1, 2, 3, 4, 5])

In [99]:
v-1

array([0, 1, 2, 3, 4])

In [100]:
v*5

array([ 5, 10, 15, 20, 25])

In [101]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [102]:
v*5/10-1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [103]:
#ufunc

In [104]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [105]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [106]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [107]:
np.power(v,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [108]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [109]:
np.absolute(np.array([-3]))

array([3])

In [110]:
np.sin(360)

0.9589157234143065

In [111]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [112]:
np.log2(v), np.log10(v)

(array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809]),
 array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ]))

###  <font color='red'>Two unknown equation solution with numpy</font> 
5*x0 + x1=12

x0 + 3*x1=10

In [113]:
a=np.array([[5,1],[1,3]])
b=np.array([12,10])
x= np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])